### ISSUE TITLE
running status in scheduler

### ISSUE THREAD

**Issue by reznr1369** [niphlod/w2p_scheduler_tests#4]
hi
when do a task in scheduler_task (that have QUEUED status)  go to the RUNNING status?
for example i want send sms after 15min... but my task in queue always is in QUEUED status.

**Comment by niphlod** [comment]
did you start the scheduler with web2py.py -K appname ?

BTW: ask in https://groups.google.com/forum/#!forum/web2py if the bug isn't related to this very application
